// adminModules.js — shared catalog of AdminTools modules.
// TABS  = every admin module ({ id, label, color }).
// GROUPS = category grouping ({ name, icon, module, ids }).
// Used by AdminTools (its module sidebar) and AdminHome (the Tools rail submenu).

export const TABS = [
  { id: "dashboard", label: "📊 Owner Dashboard", color: "#F59E0B" },
  { id: "optimization", label: "📈 Optimization Center", color: "#0ea5e9" },
  { id: "staff", label: "👤 Staff & PIN", color: "#F59E0B" },
  { id: "gudang", label: "📦 Gudang & Stok", color: "#3B82F6" },
  { id: "waste", label: "🗑️ Log Waste", color: "#F97316" },
  { id: "config", label: "⚙️ Konfigurasi", color: "#A78BFA" },
  { id: "audit", label: "📋 Audit Trail", color: "#14B8A6" },
  { id: "master", label: "🍽️ Master Item", color: "#EC4899" },
  { id: "finance", label: "💰 Finance", color: "#10B981" },
  { id: "menu_builder", label: "🧱 Menu Builder", color: "#8B5CF6" },
  { id: "procurement_plus", label: "🚚 Procurement+", color: "#06B6D4" },
  { id: "aggregator", label: "🛵 Aggregator", color: "#FB7185" },
  { id: "payment", label: "💳 Payment Gateway", color: "#22D3EE" },
  { id: "loyalty", label: "🏅 Loyalty", color: "#FBBF24" },
  { id: "cashier_kpi", label: "📊 KPI Kasir", color: "#34D399" },
  { id: "checklist", label: "✅ Checklist", color: "#10B981" },
  { id: "hris", label: "👥 HRIS", color: "#A78BFA" },
  { id: "broadcast", label: "📣 Broadcast", color: "#f97316" },
  { id: "price_list", label: "💲 Price List", color: "#10b981" },
  { id: "goods_delivery", label: "🚚 Good Delivery", color: "#06B6D4" },
  { id: "goods_received", label: "📥 Good Received", color: "#0e7490" },
  { id: "stock_opname", label: "📋 Stock Opname", color: "#0891b2" },
  { id: "production", label: "🏭 Production", color: "#9a3412" },
  { id: "stock_transfer", label: "🔄 Stock Transfer", color: "#2563eb" },
  { id: "batch_tracking", label: "📅 Batch & Expiry", color: "#ca8a04" },
  { id: "outlet_master", label: "🏪 Outlet Master", color: "#15803d" },
  { id: "incidents", label: "🚨 Incident", color: "#dc2626" },
  { id: "escalation", label: "🚨 Escalation Matrix", color: "#ef4444" },
  { id: "cinema_ops", label: "🎬 Cinema Ops", color: "#a855f7" },
  { id: "signage", label: "📺 Digital Signage", color: "#9333ea" },
  { id: "demand_forecast", label: "📈 Demand Forecast", color: "#0284c7" },
  { id: "asset_maintenance", label: "🔧 Asset & Maintenance", color: "#78716c" },
  { id: "shift_roster", label: "📆 Shift Roster", color: "#059669" },
  { id: "notif_center", label: "🔔 Notification Center", color: "#db2777" },
  { id: "auto_reorder", label: "🔁 Auto-Reorder", color: "#3730a3" },
  { id: "purchase_return", label: "↩️ Purchase Return", color: "#be123c" },
  { id: "internal_return", label: "🔁 Internal Return", color: "#9f1239" },
  { id: "stock_list", label: "📃 Stock List", color: "#155e75" },
  { id: "quotation", label: "💬 Quotation", color: "#6366f1" },
  { id: "sales_order", label: "📑 Sales Order", color: "#6d28d9" },
  { id: "delivery_order", label: "🚛 Delivery Order", color: "#0891b2" },
  { id: "sales_invoice", label: "🧾 Sales Invoice", color: "#4338ca" },
  { id: "sales_return", label: "↪️ Sales Return", color: "#7e22ce" },
  { id: "b2b_customer", label: "🏢 B2B Customer", color: "#5b21b6" },
  { id: "sales_stock_sync", label: "🔗 Sales→Stock Sync", color: "#14b8a6" },
  { id: "simple_purchase", label: "🛒 Simple Purchase", color: "#65a30d" },
  { id: "petty_cash", label: "💵 Petty Cash", color: "#d97706" },
  { id: "purchase_invoice", label: "🧾 Invoice", color: "#a78bfa" },
  { id: "settlement", label: "🧮 Settlement", color: "#10b981" },
  { id: "journal", label: "📓 Jurnal", color: "#a78bfa" },
  { id: "coa", label: "📚 Chart of Accounts", color: "#1d4ed8" },
  { id: "general_ledger", label: "📒 General Ledger", color: "#0369a1" },
  { id: "reconciliation", label: "⚖️ Reconciliation", color: "#0d9488" },
  { id: "release_payment", label: "💸 Release Payment", color: "#c2410c" },
  { id: "period_closing", label: "🔒 Tutup Periode", color: "#64748b" },
  { id: "fin_statements", label: "📊 Lap. Keuangan", color: "#10b981" },
  { id: "finance_center", label: "💹 Finance Center", color: "#10b981" },
  { id: "finance_alert", label: "🚨 Finance Alert", color: "#ef4444" },
  { id: "ar", label: "📥 Piutang AR", color: "#3b82f6" },
  { id: "budget", label: "🎯 Budget", color: "#a78bfa" },
  { id: "budget_plan", label: "📋 Budget Plan", color: "#4f46e5" },
  { id: "payroll", label: "💼 Payroll", color: "#06B6D4" },
  { id: "franchise", label: "🏛️ Franchise", color: "#fbbf24" },
  { id: "consolidation", label: "🏛️ Konsolidasi", color: "#1e40af" },
  { id: "core_tax", label: "🧾 Core Tax", color: "#b91c1c" },
  { id: "cash_flow", label: "💧 Laporan Arus Kas", color: "#0d9488" },
  { id: "ap_aging", label: "📑 AP Aging", color: "#dc2626" },
  { id: "supplier_master", label: "🏭 Supplier Master", color: "#8b5cf6" },
  { id: "compliance", label: "📋 Compliance & Izin", color: "#15803d" },
  { id: "sales_pipeline", label: "🎯 Sales Pipeline", color: "#6366f1" },
  { id: "contract", label: "📄 Contract Mgmt", color: "#ca8a04" },
  { id: "rfq", label: "📨 RFQ / Tender", color: "#0891b2" },
  { id: "risk", label: "⚠️ Risk Management", color: "#dc2626" },
  { id: "quality", label: "🛡️ Quality & Food Safety", color: "#16a34a" },
  { id: "internal_audit", label: "🔍 Internal Audit", color: "#7c3aed" },
  { id: "document_hub", label: "📚 Document / SOP Hub", color: "#0891b2" },
  { id: "helpdesk", label: "🎫 Helpdesk / Complaint", color: "#f97316" },
  { id: "food_cost", label: "🍳 Food Cost", color: "#f97316" },
  { id: "conv_fee", label: "🧾 Biaya Layanan", color: "#fb923c" },
  { id: "reward", label: "🎮 Reward", color: "#a855f7" },
  { id: "reward_benefit", label: "🎁 Reward Benefit", color: "#ec4899" },
  { id: "motivation", label: "🧠 Motivasi", color: "#22c55e" },
  { id: "hr_command", label: "🏥 HR Command", color: "#14b8a6" },
  { id: "anti_fraud", label: "🛡️ Anti-Fraud", color: "#ef4444" },
  { id: "talenta", label: "🔗 Talenta", color: "#0ea5e9" },
  { id: "customer_intel", label: "🎯 Customer Intel", color: "#d946ef" },
  { id: "mkt_behavior", label: "📊 Behavior", color: "#22d3ee" },
  { id: "loyalty_promo", label: "🎁 Loyalty & Promo", color: "#f43f5e" },
  { id: "feedback_segment", label: "💬 Feedback", color: "#eab308" },
  { id: "clv_churn", label: "📉 CLV & Churn", color: "#10b981" },
  { id: "geo_engage", label: "🗺️ Geo & Journey", color: "#6366f1" },
  { id: "campaign", label: "📡 Campaign", color: "#fb7185" },
  { id: "rbac", label: "🔐 Roles & Akses", color: "#a855f7" },
  { id: "approval", label: "⚖️ Approval", color: "#f59e0b" },
  { id: "device_session", label: "🖥️ Device & Sesi", color: "#3b82f6" },
  { id: "security", label: "🛡️ Security", color: "#e11d48" },
  { id: "role_dash", label: "📊 Role Dashboard", color: "#818cf8" },
  { id: "self_audit", label: "🔎 Self-Audit", color: "#16a34a" },
  { id: "item_master", label: "📦 Item Master", color: "#0891b2" },
  { id: "master_unit", label: "📐 Master Unit", color: "#0e7490" },
  { id: "master_category", label: "🗂️ Master Category", color: "#0891b2" },
  { id: "food_cost_calc", label: "🧮 Food Cost Calc", color: "#ea580c" },
  { id: "item_pricing", label: "💲 Item Pricing", color: "#22c55e" },
  { id: "item_config", label: "🔧 Item Config", color: "#0d9488" },
  { id: "item_rules", label: "🍽️ Item Rules", color: "#ea580c" },
  { id: "item_intel", label: "🩺 Item Health", color: "#16a34a" },
  { id: "product_hub", label: "🛍️ Product Hub", color: "#8b5cf6" },
  { id: "product_ver", label: "📜 Versioning", color: "#7c3aed" },
];

// Urutan value-chain enterprise: Operasi → Product → Inventory → Commerce
// → Finance → HRIS → Customer → Security. Tiap grup urut alur kerja.
export const GROUPS = [
  { name: "Dashboard", icon: "📊", module: "pos", ids: ["dashboard", "optimization"] },
  { name: "Operasi & Outlet", icon: "🛰️", module: "pos", ids: ["outlet_master", "staff", "checklist", "cashier_kpi", "gudang", "waste", "asset_maintenance", "quality", "incidents", "escalation", "cinema_ops", "compliance", "document_hub", "notif_center", "config", "audit"] },
  { name: "Product", icon: "📦", module: "config", ids: ["master_category", "master_unit", "item_master", "item_pricing", "item_config", "item_rules", "food_cost", "food_cost_calc", "item_intel", "product_hub", "product_ver"] },
  { name: "Inventory & Procurement", icon: "🚚", module: "stock", ids: ["stock_list", "batch_tracking", "stock_opname", "stock_transfer", "production", "sales_stock_sync", "demand_forecast", "auto_reorder", "supplier_master", "rfq", "price_list", "procurement_plus", "simple_purchase", "petty_cash", "goods_delivery", "goods_received", "purchase_invoice", "purchase_return", "internal_return"] },
  { name: "Commerce", icon: "🛒", module: "pos", ids: ["master", "menu_builder", "payment", "conv_fee", "aggregator", "loyalty", "broadcast", "sales_pipeline", "b2b_customer", "quotation", "sales_order", "delivery_order", "sales_invoice", "sales_return"] },
  { name: "Finance", icon: "💰", module: "finance", ids: ["coa", "general_ledger", "journal", "settlement", "reconciliation", "release_payment", "ar", "ap_aging", "finance", "fin_statements", "cash_flow", "finance_center", "finance_alert", "budget", "budget_plan", "period_closing", "consolidation", "core_tax", "franchise"] },
  { name: "HRIS & Reward", icon: "👥", module: "hr", ids: ["hris", "shift_roster", "payroll", "talenta", "reward", "reward_benefit", "motivation", "hr_command"] },
  { name: "Customer & Marketing", icon: "🎯", module: "marketing", ids: ["customer_intel", "mkt_behavior", "clv_churn", "feedback_segment", "geo_engage", "loyalty_promo", "campaign", "signage", "helpdesk"] },
  { name: "Security & Admin", icon: "🔐", module: "rbac", ids: ["rbac", "role_dash", "approval", "device_session", "security", "contract", "risk", "internal_audit", "anti_fraud", "self_audit"] },
];
